/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import controller.ProjectController;
import java.util.Date;
import model.Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
//        ProjectController projectController = new ProjectController();
//        Project project = new Project();
//        project.setName("Projeto Raul");
//        project.setDescription("Descrição do projeto Teste");
//        project.setCreatedAt(new Date());
//        project.setUpdatedAt(new Date());
//        projectController.save(project);
    }
}
